# Generated by Django 5.1.2 on 2025-01-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_address_customuser_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
    ]
