# Generated by Django 5.1.2 on 2024-11-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals_downline",
                to="affiliates.affiliate",
            ),
        ),
    ]
