# Generated by Django 5.1.2 on 2024-12-02 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earning_type",
                    models.CharField(
                        choices=[
                            ("product", "Product Commission"),
                            ("referral", "Referral Commission"),
                            ("rank", "Rank Reward"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="affiliates.affiliate",
                    ),
                ),
            ],
        ),
    ]
