# Generated by Django 5.1.2 on 2024-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmodule",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
