# Generated by Django 5.1.2 on 2024-12-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_alter_trainingmodule_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="videos",
            field=models.ManyToManyField(blank=True, to="training.trainingvideo"),
        ),
    ]
