# Generated by Django 5.1.2 on 2024-12-02 12:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Default Price"
                    ),
                ),
                (
                    "default_commission",
                    models.CharField(
                        help_text="Comma-separated percentages, e.g., 5%, 2%",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\\d+%,?)+$",
                                "Enter valid comma-separated percentages.",
                            )
                        ],
                        verbose_name="Default Commission",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("e-commerce", "E-Commerce"),
                            ("cms", "CMS"),
                            ("legal", "Legal"),
                            ("education", "Education"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
                (
                    "sales_note",
                    models.TextField(
                        blank=True, help_text="Noted when sales occur", null=True
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        help_text="Keywords to describe the product for search optimization"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AffiliateProductLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_url", models.URLField(unique=True)),
                ("clicks", models.PositiveIntegerField(default=0)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="affiliates.affiliate",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commission_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "affiliate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="affiliates.affiliate",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
