# Generated by Django 5.1.2 on 2024-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpurchase",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productpurchase",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
